### ISSUE TITLE
Can't pull Ubuntu image

### ISSUE THREAD

**Issue by pauldraper** [bazel-contrib/rules_oci#151]
I try to pull an Ubuntu image from DockerHub.

```bzl
oci_pull(
    name = "ubuntu",
    tag = "latest",
    image = "index.docker.io/library/ubuntu",
    platforms = [
        "linux/amd64",
    ],
)
```

I run:

```sh
bazel run @ubuntu_unpinned//:pin
```

It fails:

```
paul@Pauls-MBP redoapp % bazel run @ubuntu_unpinned//:pin
INFO: Invocation ID: 92366a73-2771-4d90-a1e8-d5c1adc254c8
DEBUG: /private/var/tmp/_bazel_paul/5a5efa90f7fa1e8cbf1caad71f9e5c69/external/rules_oci/oci/pull.bzl:235:14: 
WARNING: fetching from https://index.docker.io/v2/library/ubuntu/manifests/latest without an integrity hash. The result will not be cached.
INFO: Repository ubuntu_unpinned instantiated at:
  /Users/paul/Dev/redoapp/redoapp/WORKSPACE.bazel:206:23: in <toplevel>
  /Users/paul/Dev/redoapp/redoapp/tools/container/workspace.bzl:4:13: in container_repositories
  /private/var/tmp/_bazel_paul/5a5efa90f7fa1e8cbf1caad71f9e5c69/external/rules_oci/oci/pull.bzl:582:16: in oci_pull
Repository rule pin_tag defined at:
  /private/var/tmp/_bazel_paul/5a5efa90f7fa1e8cbf1caad71f9e5c69/external/rules_oci/oci/pull.bzl:527:26: in <toplevel>
WARNING: Download from https://index.docker.io/v2/library/ubuntu/manifests/latest failed: class java.io.FileNotFoundException GET returned 404 Not Found
ERROR: An error occurred during the fetch of repository 'ubuntu_unpinned':
   Traceback (most recent call last):
        File "/private/var/tmp/_bazel_paul/5a5efa90f7fa1e8cbf1caad71f9e5c69/external/rules_oci/oci/pull.bzl", line 512, column 33, in _pin_tag_impl
                downloader.download_manifest(rctx.attr.tag, "manifest_list.json")
        File "/private/var/tmp/_bazel_paul/5a5efa90f7fa1e8cbf1caad71f9e5c69/external/rules_oci/oci/pull.bzl", line 282, column 74, in lambda
                download_manifest = lambda identifier, output: _download_manifest(rctx, state, identifier, output),
        File "/private/var/tmp/_bazel_paul/5a5efa90f7fa1e8cbf1caad71f9e5c69/external/rules_oci/oci/pull.bzl", line 248, column 14, in _download_manifest
                _download(rctx, state, identifier, output, "manifests")
        File "/private/var/tmp/_bazel_paul/5a5efa90f7fa1e8cbf1caad71f9e5c69/external/rules_oci/oci/pull.bzl", line 237, column 20, in _download
                download_fn(
        File "/private/var/tmp/_bazel_paul/5a5efa90f7fa1e8cbf1caad71f9e5c69/external/rules_oci/oci/private/download.bzl", line 117, column 25, in _bazel_download
                return rctx.download(**kwargs)
Error in download: java.io.IOException: Error downloading [https://index.docker.io/v2/library/ubuntu/manifests/latest] to /private/var/tmp/_bazel_paul/5a5efa90f7fa1e8cbf1caad71f9e5c69/external/ubuntu_unpinned/manifest_list.json: GET returned 404 Not Found
ERROR: /Users/paul/Dev/redoapp/redoapp/WORKSPACE.bazel:206:23: fetching pin_tag rule //external:ubuntu_unpinned: Traceback (most recent call last):
        File "/private/var/tmp/_bazel_paul/5a5efa90f7fa1e8cbf1caad71f9e5c69/external/rules_oci/oci/pull.bzl", line 512, column 33, in _pin_tag_impl
                downloader.download_manifest(rctx.attr.tag, "manifest_list.json")
        File "/private/var/tmp/_bazel_paul/5a5efa90f7fa1e8cbf1caad71f9e5c69/external/rules_oci/oci/pull.bzl", line 282, column 74, in lambda
                download_manifest = lambda identifier, output: _download_manifest(rctx, state, identifier, output),
        File "/private/var/tmp/_bazel_paul/5a5efa90f7fa1e8cbf1caad71f9e5c69/external/rules_oci/oci/pull.bzl", line 248, column 14, in _download_manifest
                _download(rctx, state, identifier, output, "manifests")
        File "/private/var/tmp/_bazel_paul/5a5efa90f7fa1e8cbf1caad71f9e5c69/external/rules_oci/oci/pull.bzl", line 237, column 20, in _download
                download_fn(
        File "/private/var/tmp/_bazel_paul/5a5efa90f7fa1e8cbf1caad71f9e5c69/external/rules_oci/oci/private/download.bzl", line 117, column 25, in _bazel_download
                return rctx.download(**kwargs)
Error in download: java.io.IOException: Error downloading [https://index.docker.io/v2/library/ubuntu/manifests/latest] to /private/var/tmp/_bazel_paul/5a5efa90f7fa1e8cbf1caad71f9e5c69/external/ubuntu_unpinned/manifest_list.json: GET returned 404 Not Found
ERROR: java.io.IOException: Error downloading [https://index.docker.io/v2/library/ubuntu/manifests/latest] to /private/var/tmp/_bazel_paul/5a5efa90f7fa1e8cbf1caad71f9e5c69/external/ubuntu_unpinned/manifest_list.json: GET returned 404 Not Found
INFO: Elapsed time: 0.629s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
ERROR: Build failed. Not running target
```

I'm using macOS arm64.

**Comment by thesayyn** [comment]
Oh looks like `ubuntu` images now use oci image types. This will need a fix.
