### ISSUE TITLE
`oci_pull` fails when a Docker config file is present but has no `auths` key

### ISSUE THREAD

**Issue by josephglanville** [bazel-contrib/rules_oci#171]
This is a bug because this key isn't a required key of the Docker config file and there is a good chance that only credential helpers are configured and thus `auths` would not be present.

Example traceback:
```
ERROR: An error occurred during the fetch of repository 'java_base_arm64':
   Traceback (most recent call last):
	File "/private/var/tmp/_bazel_jpg/58813bfe9c785f28433c8cbb8ece4269/external/rules_oci/oci/pull.bzl", line 324, column 36, in _oci_pull_impl
		mf, mf_len = _download_manifest(rctx, rctx.attr.identifier, mf_file)
	File "/private/var/tmp/_bazel_jpg/58813bfe9c785f28433c8cbb8ece4269/external/rules_oci/oci/pull.bzl", line 240, column 14, in _download_manifest
		_download(rctx, identifier, output, "manifests")
	File "/private/var/tmp/_bazel_jpg/58813bfe9c785f28433c8cbb8ece4269/external/rules_oci/oci/pull.bzl", line 202, column 23, in _download
		auth = _auth_basic(rctx, registry, repository, identifier)
	File "/private/var/tmp/_bazel_jpg/58813bfe9c785f28433c8cbb8ece4269/external/rules_oci/oci/pull.bzl", line 116, column 31, in _auth_basic
		for host_raw in config["auths"]:
Error: key "auths" not found in dictionary
```

Fix is likely to skip trying to configure basic auth if this key is not present.

**Comment by josephglanville** [comment]
Nevermind, this is fixed in master, was fixed in https://github.com/bazel-contrib/rules_oci/commit/0cb2353d7f792de3cd2be9e950f7dcfe63a3b680
