### ISSUE TITLE
How I can use oci_pull?

### ISSUE THREAD

**Issue by farcop** [bazel-contrib/rules_oci#247]
Bazel 6.1.0 @ darwin_arm64

WORKSPACE
```
...
load("@rules_oci//oci:pull.bzl", "oci_pull")

oci_pull(
    name = "node_alpine",
    registry = "docker.io",
    repository = "node",
    tag = "16.19.1-alpine3.16",
    platforms = [
        "linux/amd64",
        "linux/arm64",
    ],
)
```

I got error
```
% bazel build @node_alpine//:node_alpine      
WARNING: fetching from https://docker.io/v2/node/manifests/16.19.1-alpine3.16 without an integrity hash. The result will not be cached.
INFO: Repository node_alpine instantiated at:
  /Users/farcop/Sources/generator/WORKSPACE:212:9: in <toplevel>
  /private/var/tmp/_bazel_farcop/74ae81770375b5839f4ec747ac5eca4b/external/rules_oci/oci/pull.bzl:142:14: in oci_pull
Repository rule oci_alias defined at:
  /private/var/tmp/_bazel_farcop/74ae81770375b5839f4ec747ac5eca4b/external/rules_oci/oci/private/pull.bzl:517:28: in <toplevel>
ERROR: An error occurred during the fetch of repository 'node_alpine':
   Traceback (most recent call last):
	File "/private/var/tmp/_bazel_farcop/74ae81770375b5839f4ec747ac5eca4b/external/rules_oci/oci/private/pull.bzl", line 472, column 51, in _oci_alias_impl
		manifest, _ = downloader.download_manifest(rctx.attr.identifier, "mf.json")
	File "/private/var/tmp/_bazel_farcop/74ae81770375b5839f4ec747ac5eca4b/external/rules_oci/oci/private/pull.bzl", line 275, column 74, in lambda
		download_manifest = lambda identifier, output: _download_manifest(rctx, state, identifier, output),
	File "/private/var/tmp/_bazel_farcop/74ae81770375b5839f4ec747ac5eca4b/external/rules_oci/oci/private/pull.bzl", line 237, column 31, in _download_manifest
		manifest = json.decode(bytes)
Error in decode: at offset 0, unexpected character "<"
ERROR: /Users/farcop/Sources/generator/WORKSPACE:212:9: fetching oci_alias rule //external:node_alpine: Traceback (most recent call last):
	File "/private/var/tmp/_bazel_farcop/74ae81770375b5839f4ec747ac5eca4b/external/rules_oci/oci/private/pull.bzl", line 472, column 51, in _oci_alias_impl
		manifest, _ = downloader.download_manifest(rctx.attr.identifier, "mf.json")
	File "/private/var/tmp/_bazel_farcop/74ae81770375b5839f4ec747ac5eca4b/external/rules_oci/oci/private/pull.bzl", line 275, column 74, in lambda
		download_manifest = lambda identifier, output: _download_manifest(rctx, state, identifier, output),
	File "/private/var/tmp/_bazel_farcop/74ae81770375b5839f4ec747ac5eca4b/external/rules_oci/oci/private/pull.bzl", line 237, column 31, in _download_manifest
		manifest = json.decode(bytes)
Error in decode: at offset 0, unexpected character "<"
ERROR: at offset 0, unexpected character "<"
INFO: Elapsed time: 1.005s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
```

if I use separate def @ WORKSPACE
```
oci_pull(
    name = "node_alpine_arm64",
    digest = "sha256:e4d7718d98d73f19f97f726984b282e529ce588a43df13b53682b8d1cf16d790",
    registry = "docker.io",
    repository = "node",
)

oci_pull(
    name = "node_alpine_amd64",
    digest = "sha256:3b8a9f10adbadf7d6bb76ee6ebd5ee7b8fe93563f4b0aa6ada080025c3d19993",
    registry = "docker.io",
    repository = "node",
)
```

then I have another error
```
% bazel build @node_alpine_arm64//:node_alpine_arm64
WARNING: Could not fetch the manifest. Either there was an authentication issue or trying to pull an image with OCI image media types. 
Falling back to using `curl`. See https://github.com/bazelbuild/bazel/issues/17829 for the context.
INFO: Repository node_alpine_arm64_single instantiated at:
  /Users/farcop/Sources/generator/WORKSPACE:224:9: in <toplevel>
  /private/var/tmp/_bazel_farcop/74ae81770375b5839f4ec747ac5eca4b/external/rules_oci/oci/pull.bzl:133:18: in oci_pull
Repository rule oci_pull defined at:
  /private/var/tmp/_bazel_farcop/74ae81770375b5839f4ec747ac5eca4b/external/rules_oci/oci/private/pull.bzl:429:27: in <toplevel>
WARNING: Download from https://docker.io/v2/node/manifests/sha256:e4d7718d98d73f19f97f726984b282e529ce588a43df13b53682b8d1cf16d790 failed: class com.google.devtools.build.lib.bazel.repository.downloader.UnrecoverableHttpException Checksum was 0e54ecd5cd49d2f9f3d6b11a99d29b2ab3ceeac82cf03a4a83f14e011af74973 but wanted e4d7718d98d73f19f97f726984b282e529ce588a43df13b53682b8d1cf16d790
ERROR: An error occurred during the fetch of repository 'node_alpine_arm64_single':
   Traceback (most recent call last):
	File "/private/var/tmp/_bazel_farcop/74ae81770375b5839f4ec747ac5eca4b/external/rules_oci/oci/private/pull.bzl", line 352, column 46, in _oci_pull_impl
		mf, mf_len = downloader.download_manifest(rctx.attr.identifier, "manifest.json")
	File "/private/var/tmp/_bazel_farcop/74ae81770375b5839f4ec747ac5eca4b/external/rules_oci/oci/private/pull.bzl", line 275, column 74, in lambda
		download_manifest = lambda identifier, output: _download_manifest(rctx, state, identifier, output),
	File "/private/var/tmp/_bazel_farcop/74ae81770375b5839f4ec747ac5eca4b/external/rules_oci/oci/private/pull.bzl", line 250, column 18, in _download_manifest
		_download(
	File "/private/var/tmp/_bazel_farcop/74ae81770375b5839f4ec747ac5eca4b/external/rules_oci/oci/private/pull.bzl", line 218, column 23, in _download
		return download_fn(
	File "/private/var/tmp/_bazel_farcop/74ae81770375b5839f4ec747ac5eca4b/external/rules_oci/oci/private/download.bzl", line 83, column 35, in _download
		command.extend(_auth_to_header(url, auth))
	File "/private/var/tmp/_bazel_farcop/74ae81770375b5839f4ec747ac5eca4b/external/rules_oci/oci/private/download.bzl", line 9, column 24, in _auth_to_header
		if auth_val["type"] == "pattern":
Error: key "type" not found in dictionary
ERROR: /Users/farcop/Sources/generator/WORKSPACE:224:9: fetching oci_pull rule //external:node_alpine_arm64_single: Traceback (most recent call last):
	File "/private/var/tmp/_bazel_farcop/74ae81770375b5839f4ec747ac5eca4b/external/rules_oci/oci/private/pull.bzl", line 352, column 46, in _oci_pull_impl
		mf, mf_len = downloader.download_manifest(rctx.attr.identifier, "manifest.json")
	File "/private/var/tmp/_bazel_farcop/74ae81770375b5839f4ec747ac5eca4b/external/rules_oci/oci/private/pull.bzl", line 275, column 74, in lambda
		download_manifest = lambda identifier, output: _download_manifest(rctx, state, identifier, output),
	File "/private/var/tmp/_bazel_farcop/74ae81770375b5839f4ec747ac5eca4b/external/rules_oci/oci/private/pull.bzl", line 250, column 18, in _download_manifest
		_download(
	File "/private/var/tmp/_bazel_farcop/74ae81770375b5839f4ec747ac5eca4b/external/rules_oci/oci/private/pull.bzl", line 218, column 23, in _download
		return download_fn(
	File "/private/var/tmp/_bazel_farcop/74ae81770375b5839f4ec747ac5eca4b/external/rules_oci/oci/private/download.bzl", line 83, column 35, in _download
		command.extend(_auth_to_header(url, auth))
	File "/private/var/tmp/_bazel_farcop/74ae81770375b5839f4ec747ac5eca4b/external/rules_oci/oci/private/download.bzl", line 9, column 24, in _auth_to_header
		if auth_val["type"] == "pattern":
Error: key "type" not found in dictionary
ERROR: /private/var/tmp/_bazel_farcop/74ae81770375b5839f4ec747ac5eca4b/external/node_alpine_arm64/BUILD.bazel:1:6: @node_alpine_arm64//:node_alpine_arm64 depends on @node_alpine_arm64_single//:node_alpine_arm64_single in repository @node_alpine_arm64_single which failed to fetch. no such package '@node_alpine_arm64_single//': key "type" not found in dictionary
ERROR: Analysis of target '@node_alpine_arm64//:node_alpine_arm64' failed; build aborted: Analysis failed
INFO: Elapsed time: 1.455s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded, 0 targets configured)
```

**Comment by farcop** [comment]
I used digests from docker command
```
% docker manifest inspect node:16.19.1-alpine3.16   
{
   "schemaVersion": 2,
   "mediaType": "application/vnd.docker.distribution.manifest.list.v2+json",
   "manifests": [
      {
         "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
         "size": 1158,
         "digest": "sha256:3b8a9f10adbadf7d6bb76ee6ebd5ee7b8fe93563f4b0aa6ada080025c3d19993",
         "platform": {
            "architecture": "amd64",
            "os": "linux"
         }
      },
      {
         "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
         "size": 1158,
         "digest": "sha256:ce4ca76ccad37f6aa7655803b9a78460a23092abc678f2fed1ee68caae4bf398",
         "platform": {
            "architecture": "arm",
            "os": "linux",
            "variant": "v6"
         }
      },
      {
         "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
         "size": 1158,
         "digest": "sha256:45caf8c37604e5d3659cbe08bc3564a22051c54c10394054fcb120be4e898068",
         "platform": {
            "architecture": "arm",
            "os": "linux",
            "variant": "v7"
         }
      },
      {
         "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
         "size": 1158,
         "digest": "sha256:268d8c4603b1b48f759b9fde9e0b9aa77919b799d1a1180c65ecece6cd198e34",
         "platform": {
            "architecture": "arm64",
            "os": "linux",
            "variant": "v8"
         }
      },
      {
         "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
         "size": 1158,
         "digest": "sha256:63e69bce11123eb7adc077dd3783a3ab87bccc1142d88dcac885f2414561aee1",
         "platform": {
            "architecture": "ppc64le",
            "os": "linux"
         }
      },
      {
         "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
         "size": 1158,
         "digest": "sha256:d58288491e42773dcd2a6d17eec425690996919cf6c75e8b7657b9e4626e2701",
         "platform": {
            "architecture": "s390x",
            "os": "linux"
         }
      }
   ]
}
```

**Comment by thesayyn** [comment]
> oci_pull(
>     name = "node_alpine",
>     image = "node:16.19.1-alpine3.16",
>     platforms = [
>         "linux/amd64",
>         "linux/arm64",
>     ],
> )

**Comment by farcop** [comment]
Thanks for clarification!
The working version is
```
oci_pull(
     name = "node_alpine",
     image = "node:16.19.1-alpine3.16",
     platforms = [
         "linux/amd64",
         "linux/arm64/v8",
     ],
)
```
