### ISSUE TITLE
auth_config_locator points to non-existent file

### ISSUE THREAD

**Issue by alexeagle** [bazel-contrib/rules_oci#270]
I get an error like this on a machine where the `external` folders have been restored from a cache:

```
: fetching o***_alias rule //external:aws_lambda_python: Traceback (most recent call last):
	File "/mnt/ephemeral/output/__main__/external/rules_oci/oci/private/pull.bzl", line 474, column 36, in _o***_alias_impl
		downloader = _create_downloader(rctx)
	File "/mnt/ephemeral/output/__main__/external/rules_oci/oci/private/pull.bzl", line 274, column 40, in _create_downloader
		"config": json.decode(rctx.read(rctx.attr.config)),
Error in read: Not a regular file: /mnt/ephemeral/output/__main__/external/oci_auth_config/config.json
```

**Comment by Sovietaced** [comment]
We may be encountering something similar. 

```
(17:14:45) ERROR: An error occurred during the fetch of repository 'rules_oci~1.2.0~oci~ubuntu_image':
   Traceback (most recent call last):
	File "/build_cache/external/rules_oci~1.2.0/oci/private/pull.bzl", line 475, column 36, in _oci_alias_impl
		downloader = _create_downloader(rctx)
	File "/build_cache/external/rules_oci~1.2.0/oci/private/pull.bzl", line 274, column 40, in _create_downloader
		"config": json.decode(rctx.read(rctx.attr.config)),
Error in read: Not a regular file: /build_cache/external/rules_oci~1.2.0~oci~oci_auth_config/config.json
(17:14:45) ERROR: <builtin>: fetching oci_alias rule @rules_oci~1.2.0//oci:rules_oci~1.2.0~oci~ubuntu_image: Traceback (most recent call last):
	File "/build_cache/external/rules_oci~1.2.0/oci/private/pull.bzl", line 475, column 36, in _oci_alias_impl
		downloader = _create_downloader(rctx)
	File "/build_cache/external/rules_oci~1.2.0/oci/private/pull.bzl", line 274, column 40, in _create_downloader
		"config": json.decode(rctx.read(rctx.attr.config)),
Error in read: Not a regular file: /build_cache/external/rules_oci~1.2.0~oci~oci_auth_config/config.json
```
