### ISSUE TITLE
JSON decode error using oci_pull

### ISSUE THREAD

**Issue by wevonosky** [bazel-contrib/rules_oci#445]
I am using the `oci_pull` rule like the following:

```
oci_pull(
        name = "python_base",
        registry = "docker.io",
        repository = "python",
        tag = PYTHON_VERSION,
    )
```

where PYTHON_VERSION is the string "3.10". 

If I try to run this target like `bazel run @python_base` I get the following error which looks like a json decode issue?

```
WARNING: Fetching from https://docker.io/v2/python/manifests/3.10 without an integrity hash. The result will not be cached.
INFO: Repository python_base instantiated at:
  /home/ubuntu/repos/org-monorepo/WORKSPACE.bazel:124:17: in <toplevel>
  /home/ubuntu/repos/org-monorepo/rules/oci/base_images.bzl:13:13: in load_base_images
  /home/ubuntu/.cache/bazel/_bazel_ubuntu/f8b4c447e3fde34ed339997a8bb303b1/external/rules_oci/oci/pull.bzl:143:14: in oci_pull
Repository rule oci_alias defined at:
  /home/ubuntu/.cache/bazel/_bazel_ubuntu/f8b4c447e3fde34ed339997a8bb303b1/external/rules_oci/oci/private/pull.bzl:527:28: in <toplevel>
ERROR: An error occurred during the fetch of repository 'python_base':
   Traceback (most recent call last):
        File "/home/ubuntu/.cache/bazel/_bazel_ubuntu/f8b4c447e3fde34ed339997a8bb303b1/external/rules_oci/oci/private/pull.bzl", line 476, column 55, in _oci_alias_impl
                manifest, _, digest = downloader.download_manifest(rctx.attr.identifier, "mf.json")
        File "/home/ubuntu/.cache/bazel/_bazel_ubuntu/f8b4c447e3fde34ed339997a8bb303b1/external/rules_oci/oci/private/pull.bzl", line 324, column 74, in lambda
                download_manifest = lambda identifier, output: _download_manifest(rctx, state, identifier, output),
        File "/home/ubuntu/.cache/bazel/_bazel_ubuntu/f8b4c447e3fde34ed339997a8bb303b1/external/rules_oci/oci/private/pull.bzl", line 272, column 31, in _download_manifest
                manifest = json.decode(bytes)
Error in decode: at offset 0, unexpected character "<"
ERROR: /home/ubuntu/repos/org-monorepo/WORKSPACE.bazel:124:17: fetching oci_alias rule //external:python_base: Traceback (most recent call last):
        File "/home/ubuntu/.cache/bazel/_bazel_ubuntu/f8b4c447e3fde34ed339997a8bb303b1/external/rules_oci/oci/private/pull.bzl", line 476, column 55, in _oci_alias_impl
                manifest, _, digest = downloader.download_manifest(rctx.attr.identifier, "mf.json")
        File "/home/ubuntu/.cache/bazel/_bazel_ubuntu/f8b4c447e3fde34ed339997a8bb303b1/external/rules_oci/oci/private/pull.bzl", line 324, column 74, in lambda
                download_manifest = lambda identifier, output: _download_manifest(rctx, state, identifier, output),
        File "/home/ubuntu/.cache/bazel/_bazel_ubuntu/f8b4c447e3fde34ed339997a8bb303b1/external/rules_oci/oci/private/pull.bzl", line 272, column 31, in _download_manifest
                manifest = json.decode(bytes)
Error in decode: at offset 0, unexpected character "<"
ERROR: at offset 0, unexpected character "<"
INFO: Elapsed time: 0.548s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
ERROR: Build failed. Not running target
```

**Comment by thesayyn** [comment]
` registry = "docker.io"` is wrong here, it should be `index.docker.io`

**Comment by thesayyn** [comment]
@alexeagle we should alias `docker.io` to `index.docker.io`

**Comment by wevonosky** [comment]
Thanks for that, I still get an error (albeit a different one) if I change the registry to `index.docker.io` though.

**Comment by thesayyn** [comment]
That's a different error than this one then.

> I'll try and debug this one since its maybe a problem on my system

Most likely an authentication issue.

**Comment by thesayyn** [comment]
Closing this as there is no action to take here.
