### ISSUE TITLE
oci_pull() fails with "The registry sent a manifest with schemaVersion=1" when using v2.0.0-beta2

### ISSUE THREAD

**Issue by axeluhlig** [bazel-contrib/rules_oci#678]
```
ERROR: An error occurred during the fetch of repository 'XXXX':
   Traceback (most recent call last):
        File "/XXXX/add213d47f356bb98a5d312a4234081b/external/rules_oci/oci/private/pull.bzl", line 353, column 55, in _oci_alias_impl
                manifest, _, digest = downloader.download_manifest(rctx.attr.identifier, "mf.json")
        File "/XXXX/add213d47f356bb98a5d312a4234081b/external/rules_oci/oci/private/pull.bzl", line 163, column 74, in lambda
                download_manifest = lambda identifier, output: _download_manifest(rctx, authn, identifier, output),
        File "/XXXX/add213d47f356bb98a5d312a4234081b/external/rules_oci/oci/private/pull.bzl", line 149, column 17, in _download_manifest
                fail(SCHEMA1_ERROR)
Error in fail: The registry sent a manifest with schemaVersion=1. 
This commonly occurs when fetching from a registry that needs the Docker-Distribution-API-Version header to be set.
See: https://github.com/bazel-contrib/rules_oci/blob/main/docs/pull.md#authentication-using-credential-helpers
```

When using `v1.8.0` `oci_pull()` works perfectly, when updating to `v2.0.0-beta2` I get the error above. 

Was there some change in regards to authentication between v.1.8 and v2.0?

**Comment by axeluhlig** [comment]
I just found https://github.com/bazel-contrib/rules_oci/issues/456

> Drop curl fallback for oci_pull, now that feat: add support for arbitrary headers rctx.download[_and_extract] bazelbuild/bazel#19501 is fixed.

So I assume this + https://github.com/bazel-contrib/rules_oci/issues/674 explains the error I am getting.
